### numpy.matrix

class numpy.matrix(data, dtype=None, copy=True)

In [1]:
import numpy as np

In [2]:
a = np.matrix('1 2; 3 4')
print(a)

[[1 2]
 [3 4]]


In [4]:
np.matrix([[1, 2], [3, 4]])

matrix([[1, 2],
        [3, 4]])

In [6]:
a.T

matrix([[1, 3],
        [2, 4]])

In [9]:
a.transpose()

matrix([[1, 3],
        [2, 4]])

In [11]:
b = np.matrix([[3,4],[4,5]])
b

matrix([[3, 4],
        [4, 5]])

In [13]:
a+b

matrix([[4, 6],
        [7, 9]])

In [15]:
a-b

matrix([[-2, -2],
        [-1, -1]])

In [17]:
a*b

matrix([[11, 14],
        [25, 32]])

In [20]:
a**2

matrix([[ 7, 10],
        [15, 22]])

In [21]:
a/b

matrix([[0.33333333, 0.5       ],
        [0.75      , 0.8       ]])

In [22]:
a//b

matrix([[0, 0],
        [0, 0]], dtype=int32)

In [23]:
a%b

matrix([[1, 2],
        [3, 4]], dtype=int32)

In [24]:
a==b

matrix([[False, False],
        [False, False]])

In [26]:
a!=b

matrix([[ True,  True],
        [ True,  True]])

In [28]:
a<b

matrix([[ True,  True],
        [ True,  True]])

In [30]:
a>b

matrix([[False, False],
        [False, False]])

In [32]:
a<=b

matrix([[ True,  True],
        [ True,  True]])

In [34]:
a>=b

matrix([[False, False],
        [False, False]])

In [37]:
np.min(a)

1

In [39]:
np.max(a)

4

In [41]:
np.lexsort(a)

array([[0, 1]], dtype=int64)

In [43]:
a.I

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [45]:
a.T

matrix([[1, 3],
        [2, 4]])

In [47]:
a.A1

array([1, 2, 3, 4])

In [49]:
a.base

array([[1, 2],
       [3, 4]])

In [51]:
a.data

In [65]:
a.dtype

dtype('int32')

In [66]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [67]:
x = np.matrix(np.arange(12).reshape((3,4)))
x

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [68]:
x.prod()

0

In [69]:
x.prod(0)

matrix([[  0,  45, 120, 231]])

In [71]:
a = np.eye(2)
b = np.ones((2, 2)) * 2
a.dot(b)

array([[2., 2.],
       [2., 2.]])

In [84]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [85]:
a.diagonal()

array([ 0,  5, 10, 15])

In [87]:
a.diagonal(1)


array([ 1,  6, 11])

In [88]:
a.diagonal(3)

array([3])

##### Attributes:	
A
Return self as an ndarray object.

A1
Return self as a flattened ndarray.

H
Returns the (complex) conjugate transpose of self.

I
Returns the (multiplicative) inverse of invertible self.

T
Returns the transpose of the matrix.

base
Base object if memory is from some other object.

ctypes
An object to simplify the interaction of the array with the ctypes module.

data
Python buffer object pointing to the start of the array’s data.

dtype
Data-type of the array’s elements.

flags
Information about the memory layout of the array.

flat
A 1-D iterator over the array.

imag
The imaginary part of the array.

itemsize
Length of one array element in bytes.

nbytes
Total bytes consumed by the elements of the array.

ndim
Number of array dimensions.

real
The real part of the array.

shape
Tuple of array dimensions.

size
Number of elements in the array.

strides
Tuple of bytes to step in each dimension when traversing an array.