##### One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [2]:
import numpy as np

In [3]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [4]:
a[0] # index

0

In [5]:
a[2:5]  # Slice

array([ 8, 27, 64], dtype=int32)

In [6]:
a[ : :-1]  # Extended Slice

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0], dtype=int32)

In [7]:
for i in a:
    print(i**(1/3.))

0.0
1.0
2.0
3.0
3.9999999999999996
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [9]:
b = np.arange(24).reshape(2,2,3,2)
b

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]]])

In [10]:
b[0]

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [11]:
b[0][1]

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [12]:
b[0][1][0]

array([6, 7])

In [13]:
b[0][1][0][0]

6

In [17]:
b[0,1,0,0]

6

In [46]:
b[1]

array([[[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [18]:
b.ndim

4

In [19]:
b[1:]

array([[[[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]]])

In [22]:
b[1][0]

array([[12, 13],
       [14, 15],
       [16, 17]])

In [26]:
b[1][0][1:3] 

array([[14, 15],
       [16, 17]])

In [27]:
b[1,0][1:3] 

array([[14, 15],
       [16, 17]])

In [24]:
b

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]]])

In [61]:
b[1][0][1:3]

array([[14, 15],
       [16, 17]])

###### Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:

In [35]:
def f(x,y):
    return x+y
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [36]:
b.ndim

2

In [37]:
b[1,3]

4

In [38]:
b[0:5, 1]                       # each row in the second column of b

array([1, 2, 3, 4, 5])

In [39]:
b[ : ,1]                        # equivalent to the previous example

array([1, 2, 3, 4, 5])

In [40]:
b[1:3, : ]                      # each column in the second and third row of b

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [41]:
b[-1]                                  # the last row. Equivalent to b[-1,:]

array([4, 5, 6, 7])

In [73]:
b

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [74]:
b[-1,-1]

7

In [75]:
b

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [76]:
b[-1,-2]

6

##### Iterating over multidimensional arrays is done with respect to the first axis:

In [42]:
for row in b:
    print(row)

[0 1 2 3]
[1 2 3 4]
[2 3 4 5]
[3 4 5 6]
[4 5 6 7]


In [43]:
row.ndim

1

In [79]:
list(row)

[4, 5, 6, 7]

In [44]:
row[0]

4

In [45]:
row[0:-1]

array([4, 5, 6])

In [50]:
x = np.arange(24).reshape(2,2,3,2)*np.pi
x

array([[[[ 0.        ,  3.14159265],
         [ 6.28318531,  9.42477796],
         [12.56637061, 15.70796327]],

        [[18.84955592, 21.99114858],
         [25.13274123, 28.27433388],
         [31.41592654, 34.55751919]]],


       [[[37.69911184, 40.8407045 ],
         [43.98229715, 47.1238898 ],
         [50.26548246, 53.40707511]],

        [[56.54866776, 59.69026042],
         [62.83185307, 65.97344573],
         [69.11503838, 72.25663103]]]])

In [52]:
x[0][0]

array([[ 0.        ,  3.14159265],
       [ 6.28318531,  9.42477796],
       [12.56637061, 15.70796327]])

In [53]:
a = x[0,0]<10 
a

array([[ True,  True],
       [ True,  True],
       [False, False]])

In [54]:
b = x[0,1]>10
b

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [55]:
a+b

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [56]:
x[0]

array([[[ 0.        ,  3.14159265],
        [ 6.28318531,  9.42477796],
        [12.56637061, 15.70796327]],

       [[18.84955592, 21.99114858],
        [25.13274123, 28.27433388],
        [31.41592654, 34.55751919]]])

In [57]:
np.any(x[0])

True

In [58]:
x[1]

array([[[37.69911184, 40.8407045 ],
        [43.98229715, 47.1238898 ],
        [50.26548246, 53.40707511]],

       [[56.54866776, 59.69026042],
        [62.83185307, 65.97344573],
        [69.11503838, 72.25663103]]])

In [128]:
x[1,1]

array([[56.54866776, 59.69026042],
       [62.83185307, 65.97344573],
       [69.11503838, 72.25663103]])

In [133]:
x[1,1,1,0]

62.83185307179586

In [139]:
x[1,:2]

array([[[37.69911184, 40.8407045 ],
        [43.98229715, 47.1238898 ],
        [50.26548246, 53.40707511]],

       [[56.54866776, 59.69026042],
        [62.83185307, 65.97344573],
        [69.11503838, 72.25663103]]])

In [143]:
x[0:]

array([[[[ 0.        ,  3.14159265],
         [ 6.28318531,  9.42477796],
         [12.56637061, 15.70796327]],

        [[18.84955592, 21.99114858],
         [25.13274123, 28.27433388],
         [31.41592654, 34.55751919]]],


       [[[37.69911184, 40.8407045 ],
         [43.98229715, 47.1238898 ],
         [50.26548246, 53.40707511]],

        [[56.54866776, 59.69026042],
         [62.83185307, 65.97344573],
         [69.11503838, 72.25663103]]]])

In [150]:
x[0:1,:-1]

array([[[[ 0.        ,  3.14159265],
         [ 6.28318531,  9.42477796],
         [12.56637061, 15.70796327]]]])