#### Changing the shape of an array

An array has a shape given by the number of elements along each axis:

In [1]:
import numpy as np

In [7]:
a = np.floor(10*np.random.random((3,4)))
a

array([[2., 0., 7., 0.],
       [8., 4., 5., 4.],
       [7., 4., 9., 2.]])

In [8]:
a.reshape(4,3)

array([[2., 0., 7.],
       [0., 8., 4.],
       [5., 4., 7.],
       [4., 9., 2.]])

In [9]:
a

array([[2., 0., 7., 0.],
       [8., 4., 5., 4.],
       [7., 4., 9., 2.]])

In [10]:
a.shape = 4,3
a

array([[2., 0., 7.],
       [0., 8., 4.],
       [5., 4., 7.],
       [4., 9., 2.]])

In [13]:
a

array([[2., 0., 7.],
       [0., 8., 4.],
       [5., 4., 7.],
       [4., 9., 2.]])

In [14]:
a.T

array([[2., 0., 5., 4.],
       [0., 8., 4., 9.],
       [7., 4., 7., 2.]])

In [15]:
a.transpose()

array([[2., 0., 5., 4.],
       [0., 8., 4., 9.],
       [7., 4., 7., 2.]])

In [16]:
a.shape

(4, 3)

In [18]:
a.ravel()  # returns the array, flattened


array([2., 0., 7., 0., 8., 4., 5., 4., 7., 4., 9., 2.])

In [19]:
a.flatten()

array([2., 0., 7., 0., 8., 4., 5., 4., 7., 4., 9., 2.])

In [26]:
c =  a.reshape(6,2)  # returns the array with a modified shape
c

array([[2., 0.],
       [7., 0.],
       [8., 4.],
       [5., 4.],
       [7., 4.],
       [9., 2.]])

In [27]:
c.shape

(6, 2)

In [22]:
c.T  # returns the array, transposed

array([[2., 7., 8., 5., 7., 9.],
       [0., 0., 4., 4., 4., 2.]])

In [23]:
c.transpose()

array([[2., 7., 8., 5., 7., 9.],
       [0., 0., 4., 4., 4., 2.]])

In [28]:
a.shape

(4, 3)

In [30]:
a.T.shape

array([[2., 0., 5., 4.],
       [0., 8., 4., 9.],
       [7., 4., 7., 2.]])

In [33]:
a.reshape(3,-1)

array([[2., 0.],
       [7., 0.],
       [8., 4.],
       [5., 4.],
       [7., 4.],
       [9., 2.]])

In [34]:
a.reshape(1,-1)

array([[2., 0., 7., 0., 8., 4., 5., 4., 7., 4., 9., 2.]])

In [35]:
a.resize((2,6))
a

array([[2., 0., 7., 0., 8., 4.],
       [5., 4., 7., 4., 9., 2.]])

In [38]:
a = np.array([[1,2],[3,4]])
print(a)
a.ndim

[[1 2]
 [3 4]]


2

In [41]:
a.resize(6,2)
a

array([[1, 2],
       [3, 4],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

`np.flatten():`

Return a copy of the array collapsed into one dimension.

Parameters
----------
|order|Description|
|------|----------|
|'C' |means to flatten in row-major (C-style) order.|
|'F' |means to flatten in column-major (Fortran-style) order. |
|'A' |means to flatten in column-major    order if `a` is Fortran *contiguous* in memory,row-major order otherwise.| 
|'K' |means to flatten    `a` in the order the elements occur in memory.The default is 'C'.|

In [47]:
a

array([[1, 2],
       [3, 4],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [43]:
a.flatten('C')

array([1, 2, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0])

In [44]:
a.flatten('F')

array([1, 3, 0, 0, 0, 0, 2, 4, 0, 0, 0, 0])

In [45]:
a.flatten('A')

array([1, 2, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0])

In [46]:
a.flatten('K')

array([1, 2, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0])

In [49]:
a

array([[1, 2],
       [3, 4]])

## Transpose-like Operations 

In [48]:
a = np.zeros([3,4,5])
a

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [49]:
a.shape

(3, 4, 5)

In [35]:
np.moveaxis(a, 0, -1).shape

(4, 5, 3)

In [50]:
np.transpose(a).shape

(5, 4, 3)

In [38]:
np.swapaxes(a, 0, 1).shape

(4, 3, 5)

#### Stacking together different arrays¶

Several arrays can be stacked together along different axes:

In [1]:
np.random.random((2,2))

array([[0.78248216, 0.20223282],
       [0.9074274 , 0.76947453]])

In [2]:
a = np.floor(10*np.random.random((2,2)))
a

array([[9., 8.],
       [7., 9.]])

In [3]:
b = np.floor(10*np.random.random((2,2)))
b

array([[5., 1.],
       [5., 3.]])

In [4]:
np.vstack((a,b))

array([[9., 8.],
       [7., 9.],
       [5., 1.],
       [5., 3.]])

In [6]:
 np.hstack((a,b))

array([[9., 8., 5., 1.],
       [7., 9., 5., 3.]])

The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays:

In [7]:
from numpy import newaxis
np.column_stack((a,b))     # with 2D arrays

array([[9., 8., 5., 1.],
       [7., 9., 5., 3.]])

In [8]:
a = np.array([4.,2.])
b = np.array([3.,8.])
np.column_stack((a,b))     # returns a 2D array

array([[4., 3.],
       [2., 8.]])

In [9]:
np.hstack((a,b))           # the result is different

array([4., 2., 3., 8.])

In [47]:
a

array([4., 2.])

In [10]:
a[:,newaxis]               # this allows to have a 2D columns vector

array([[4.],
       [2.]])

In [11]:
b[:,newaxis]

array([[3.],
       [8.]])

In [13]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [14]:
np.hstack((a[:,newaxis],b[:,newaxis]))   # the result is the same

array([[4., 3.],
       [2., 8.]])

In [16]:
arrays  = [np.random.randn(3,4) for _ in range(5)]
arrays

[array([[ 1.78169611, -1.31153848,  0.13940879,  0.31160779],
        [-1.03445142,  2.12116586, -0.41353323,  0.63341637],
        [ 0.44940314, -0.05372413, -1.39088149, -0.10276161]]),
 array([[-0.11050933,  0.39207231, -0.3484244 ,  1.82931937],
        [ 2.8005236 ,  1.11752605, -0.11059685, -1.38581037],
        [ 0.50310478,  0.08209013,  0.6903262 , -0.66712009]]),
 array([[ 0.72795752, -0.78642864,  1.41058036, -2.02285063],
        [ 2.82622514,  0.5688997 , -1.07251233,  1.06105787],
        [-1.0288599 , -0.57532289,  0.38808699, -0.57864781]]),
 array([[ 0.39940277,  0.63843644,  1.01076073, -1.00939567],
        [ 0.74426024,  0.07883543,  0.3497571 , -0.0190984 ],
        [ 0.87286343, -0.43233602, -1.38823593,  0.32253032]]),
 array([[-1.33680847,  0.03441822,  0.42365024, -1.4842658 ],
        [ 1.0527846 , -0.69513799, -1.59245026, -0.60412693],
        [ 0.91533561,  1.53319375, -0.97961535, -0.82044124]])]

In [17]:
np.stack(arrays,axis=0).shape

(5, 3, 4)

In [18]:
np.stack(arrays,axis=1).shape

(3, 5, 4)

In [19]:
np.stack(arrays,axis=2).shape

(3, 4, 5)

In [20]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.dstack((a,b))    # Depth wise Stack

array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [127]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.dstack((a,b))

array([[[1, 2]],

       [[2, 3]],

       [[3, 4]]])

On the other hand, the function row_stack is equivalent to vstack for any input arrays. In general, for arrays of with more than two dimensions, hstack stacks along their second axes, vstack stacks along their first axes, and concatenate allows for an optional arguments giving the number of the axis along which the concatenation should happen.

##### Note:

In complex cases, r_ and c_ are useful for creating arrays by stacking numbers along one axis. They allow the use of range literals (“:”)

In [64]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

In [21]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [29]:
a = np.c_[np.array([[1,2,3]]), 0, 0, 0, np.array([[4,5,6]])]
a

array([[1, 2, 3, 0, 0, 0, 4, 5, 6]])

In [30]:
a.ndim

2

#### Split
Split an array into multiple sub-arrays.

Please refer to the split documentation. The only difference between these functions is that array_split allows indices_or_sections to be an integer that does not equally divide the axis. For an array of length l that should be split into n sections, it returns l % n sub-arrays of size l//n + 1 and the rest of size l//n.

In [32]:
x = np.arange(16.0).reshape(4, 4)
print(x)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


In [36]:
np.vsplit(x, 2)

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [145]:
np.vsplit(x, np.array([3,4]))

[array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15.]]),
 array([], shape=(0, 4), dtype=float64)]

In [71]:
np.hsplit(x,2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]), array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [162]:
y = np.arange(24).reshape(2,2,6)
np.dsplit(y,3)    # Depth split for 3D Data

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]), array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]), array([[[ 4,  5],
         [10, 11]],
 
        [[16, 17],
         [22, 23]]])]

In [37]:
x = np.arange(16.0)
np.array_split(x, 4)

[array([0., 1., 2., 3.]),
 array([4., 5., 6., 7.]),
 array([ 8.,  9., 10., 11.]),
 array([12., 13., 14., 15.])]

In [38]:
np.split(x,8)

[array([0., 1.]),
 array([2., 3.]),
 array([4., 5.]),
 array([6., 7.]),
 array([8., 9.]),
 array([10., 11.]),
 array([12., 13.]),
 array([14., 15.])]