When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not. This is often a source of confusion for beginners. There are three cases:

In [1]:
import numpy as np

#### No Copy at All
Simple assignments make no copy of array objects or of their data.

In [8]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
b = a            # no new object is created    
b is a           # a and b are two names for the same ndarray object

True

In [10]:
b.shape  

(12,)

In [11]:
b.shape=3,2,2        # changes the shape of a and it will effect the a
b

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [12]:
a

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [13]:
b.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [14]:
b

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [15]:
b[0]=10,20

In [16]:
b

array([[[10, 20],
        [10, 20]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [17]:
a

array([[[10, 20],
        [10, 20]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

#### View or Shallow Copy

In [18]:
c = a.view()
c

array([[[10, 20],
        [10, 20]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [19]:
c is a

False

In [20]:
c[0]=10

In [21]:
c

array([[[10, 10],
        [10, 10]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [22]:
a

array([[[10, 10],
        [10, 10]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [23]:
x = np.arange(3)
y = np.arange(3)

In [24]:
y.base is x

False

In [25]:
c.base is a # c is a view of the data owned by a

True

In [26]:
c

array([[[10, 10],
        [10, 10]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [27]:
c[0]

array([[10, 10],
       [10, 10]])

In [28]:
c[0,1] = 256   # a's data changes
c

array([[[ 10,  10],
        [256, 256]],

       [[  4,   5],
        [  6,   7]],

       [[  8,   9],
        [ 10,  11]]])

In [29]:
c

array([[[ 10,  10],
        [256, 256]],

       [[  4,   5],
        [  6,   7]],

       [[  8,   9],
        [ 10,  11]]])

In [30]:
a

array([[[ 10,  10],
        [256, 256]],

       [[  4,   5],
        [  6,   7]],

       [[  8,   9],
        [ 10,  11]]])

In [77]:
b

array([[[ 10,  10],
        [256, 256]],

       [[  4,   5],
        [  6,   7]],

       [[  8,   9],
        [ 10,  11]]])

In [31]:
s = a[ : , 1:3]               # spaces added for clarity; could also be written "s = a[:,1:3]"
s

array([[[256, 256]],

       [[  6,   7]],

       [[ 10,  11]]])

In [33]:
s[:] = 100                    # s[:] is a view of s. Note the difference between s=10 and s[:]=10
s

array([[[100, 100]],

       [[100, 100]],

       [[100, 100]]])

In [34]:
a

array([[[ 10,  10],
        [100, 100]],

       [[  4,   5],
        [100, 100]],

       [[  8,   9],
        [100, 100]]])

#### Deep Copy
The copy method makes a complete copy of the array and its data.

In [35]:
d = a.copy() # a new array object with new data is created
d is a

False

In [36]:
d.base is a                           # d doesn't share anything with a

False

In [37]:
d[0,0] = 9999
d

array([[[9999, 9999],
        [ 100,  100]],

       [[   4,    5],
        [ 100,  100]],

       [[   8,    9],
        [ 100,  100]]])

In [38]:
a

array([[[ 10,  10],
        [100, 100]],

       [[  4,   5],
        [100, 100]],

       [[  8,   9],
        [100, 100]]])

### Conversions

In [39]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
a.ndim

1

In [41]:
a.astype(np.complex128)

array([ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,
        7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j,
       14.+0.j, 15.+0.j, 16.+0.j, 17.+0.j, 18.+0.j, 19.+0.j])

In [42]:
c = np.atleast_2d(a)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [43]:
c.ndim

2

In [44]:
d = np.atleast_3d(a)
d

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19]]])

In [45]:
d.ndim

3

In [48]:
c = np.ravel(d)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
c.ndim

1

In [50]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [51]:
e = np.mat(a)
e

matrix([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19]])

In [52]:
np.asmatrix(a)

matrix([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19]])

In [53]:
np.asarray(e)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [54]:
f = 10
np.asarray(f)

array(10)

In [55]:
np.asmatrix(f)

matrix([[10]])

## Functions and Methods Overview
Here is a list of some useful NumPy functions and methods names ordered in categories. See Routines for the full list.

#### Array Creation
arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r, zeros, zeros_like
#### Conversions
ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat
#### Manipulations
array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack
#### Questions
all, any, nonzero, where
#### Ordering
argmax, argmin, argsort, max, min, ptp, searchsorted, sort
#### Operations
choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum
#### Basic Statistics
cov, mean, std, var
#### Basic Linear Algebra
cross, dot, outer, linalg.svd, vdot