#### NumPy Linear Algebra
Numpy provides the following functions to perform the different algebraic calculations on the input data.

|SN|Function|Definition|
|------|----|----------|
|1|dot()|It is used to calculate the dot product of two arrays.|
|2|vdot()|It is used to calculate the dot product of two vectors.|
|3|inner()|It is used to calculate the inner product of two arrays.|
|4|matmul()|It is used to calculate the matrix multiplication of two arrays.|
|5|det()|It is used to calculate the determinant of a matrix.|
|6|solve()|It is used to solve the linear matrix equation.|
|7|inv()|It is used to calculate the multiplicative inverse of the matrix.|

#### Simple Array Operations

In [1]:
import numpy as np

In [2]:
a = np.array([10,20,30,40,50])
b = np.array((20,30,40,50,60))
np.vdot(a,b)

7000

In [3]:
Scalar = np.array(10)
Scalar.ndim

0

In [4]:
Vector = np.array([10,20,30,40])
Vector

array([10, 20, 30, 40])

In [9]:
Vector.ndim

1

In [10]:
Vector.T

array([10, 20, 30, 40])

In [6]:
a = np.matrix([[1.0, 2.0], [3.0, 4.0]])
a

matrix([[1., 2.],
        [3., 4.]])

In [7]:
a.ndim

2

In [8]:
a.transpose()

matrix([[1., 3.],
        [2., 4.]])

In [11]:
a.T

matrix([[1., 3.],
        [2., 4.]])

In [12]:
np.linalg.inv(a)

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [9]:
from numpy.linalg import inv
a = np.array([[4,7], [2, 6]])
a

array([[4, 7],
       [2, 6]])

![](https://lh3.googleusercontent.com/-KJ2ZOE9awz4/XTfHDTssSiI/AAAAAAAAgFs/u8Z2z76FXdQW_ia55WMHTT0ebeXxXhmUACK8BGAs/s0/2019-07-23.png)

In [25]:
ainv = inv(a)
ainv

array([[ 0.6, -0.7],
       [-0.2,  0.4]])

In [15]:
a = np.array([[1,2],[3,4]])
np.linalg.det(a)

-2.0000000000000004

In [16]:
u = np.eye(2) # unit 2x2 matrix; "eye" represents "I"
u

array([[1., 0.],
       [0., 1.]])

In [17]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [18]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])
j @ j        # matrix product

array([[-1.,  0.],
       [ 0., -1.]])

In [19]:
a = np.array([[13,1],
              [4,5]])
print(a)
np.trace(a)  # trace

[[13  1]
 [ 4  5]]


18

In [20]:
x = np.nan
x

nan

In [21]:
x*3

nan

In [22]:
x-2

nan

In [23]:
a

array([[13,  1],
       [ 4,  5]])

In [24]:
y = np.array([[5.], [7.]])
np.linalg.solve(a, y)

array([[0.29508197],
       [1.16393443]])

In [26]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
x

array([2., 3.])

In [27]:
np.allclose(np.dot(a, x), b)

True

https://en.wikipedia.org/wiki/Linear_equation
    
# One Varaiable:
        aX+b= 0
        
        x = -b/a

# Two Variables
        
        ax+bx+c=0
        
        x(a+b)+c=0
        1/x = -((a+b)+c)
        
        
        
        
`Solver`
3x+x+9=0
x+2x+8=0


